routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// had to specify the whole route for the controller 
Route::resource('productos', 'App\Http\Controllers\ProductoController');
Route::resource('ventas', 'App\Http\Controllers\ventaController');

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'price',
        'expiration',
        'stock',
        'weightKg',
        'imgLink'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Venta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class venta extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'price',
        'expiration',
        'stock',
        'weightKg',
        'imgLink'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Producto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductoController extends Controller
{
    /**
     * Display a listing of the products table on DB 
     * paginating by 3
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $productos = DB::table('productos')->paginate(3);
        $count = DB::table('productos')->count();
        return view("productos.index", compact('productos', 'count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('productos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Producto::create($request->all());
        return redirect()->route('productos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Responses
     */
    public function show(Producto $producto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function edit(Producto $producto)
    {
        return view('productos.edit', compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Producto $producto){
        $request->validate(
            [
                'name' => 'required',
                'description',
                'price' => 'required',
                'expiration' => 'required',
                'stock' => 'required',
                'weightKg' => 'required',
                'imgLink' => ''
            ]
        );

        $producto->update($request->all());

        return redirect()->route('productos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Producto $producto)
    {
        $producto->destroy($producto->id);
        return redirect()->route('productos.index');
    }
}

app/Http/Controllers/VentaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Venta;
use Illuminate\Http\Request;

class VentaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        venta::create($request->all());
        return redirect()->route('ventas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ventas  $ventas
     * @return \Illuminate\Http\Response
     */
    public function show(venta $ventas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ventas  $ventas
     * @return \Illuminate\Http\Response
     */
    public function edit(Venta $ventas)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ventas  $ventas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, venta $ventas)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ventas  $ventas
     * @return \Illuminate\Http\Response
     */
    public function destroy(venta $ventas)
    {
        //
    }
}

resources/views/layout/layout.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title> @yield('title')</title>
   <link 
   rel="stylesheet" 
   href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
   integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
   crossorigin="anonymous">

   <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
</head>
<body>

   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ route('productos.index') }}">Carniceria</a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
             @yield('sectionInNav')
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

   {{-- <nav class="navbar navbar-light" style="background-color: #ff000070;">
      <a class="navbar-brand" href="{{ route('productos.index') }}">Carnicería</a>
      @yield('sectionInNav')
         <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
               
               <a class="nav-item nav-link disabled" href="#">Contacto</a>
            </div>
         </div>
      </div>
   </nav> --}}
   <hr>
   <div class="container">
      @yield('content')
   </div>


   <footer class="text-center text-white fixed-bottom" style="background-color: #21081a;">
    
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        # texto footer
        <a class="text-white" href="https://bitbucket.org/memosk8/">Memosk8</a>
      </div>

   </footer>

   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
   integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
   crossorigin="anonymous">
   </script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
   integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
   crossorigin="anonymous">
   </script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
   integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
   crossorigin="anonymous">
   </script>
</body>
</html>

resources/views/productos/create.blade.php
@extends('layout.layout')

@section('title', 'Agregar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Agregar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.store')}}" method="POST">

      @csrf  {{-- //token de seguridad --}}

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5"></textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" name="price" id="price" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date"  class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Guardar Producto">
   </form>
</div>
@endsection

resources/views/productos/edit.blade.php
@extends('layout.layout')

@section('title', 'Editar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Editar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.update', $producto->id)}}" method="POST">

      @csrf  {{-- //token de seguridad --}}
      @method('PUT')

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" value="{{ $producto->name }}" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5">{{ $producto->description }}</textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" value="{{$producto->price}}" name="price" id="" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date" value="{{$producto->price}}" class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" value="{{ $producto->stock }}" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" value="{{$producto->weightKg}}" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" value="{{ $producto->imgLink }}" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Actualizar Producto">
   </form>
</div>
@endsection

resources/views/productos/index.blade.php
@extends('layout.layout')

@section('title', 'Productos')

@section('content')

@section('sectionInNav')
    <div class="navbar nav">
        <li class="nav-item">
            <a class="nav-link nav-item active" href="#">Productos Registrados : {{ $count }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link nav-item active" style="color: blue;" href="{{ route('productos.create') }}">Registrar Producto</a>
        </li>
    </div>
@endsection

<div class="row">
    {{-- loops through all the products in products 
         variable passed from index funtion in ProductoController --}}
    @forelse ($productos as $producto)

        <div class="col-sm-4 ">
            <div class="card bg-light border-dark" style="max-width: 24rem;">
                <img src="{{ $producto->imgLink }}" class="card-img" alt="" width="50">
                <div class="card-body">
                    <h2 class="card-title"><em>{{ $producto->name }}</em></h2>
                    <p class="card-text">{{ $producto->description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">${{ $producto->price }}</li>
                    <li class="list-group-item">Stock en almacen: {{ $producto->stock }}</li>
                    <li class="list-group-item">Fecha de caducidad: {{ $producto->expiration }}</li>
                    <li class="list-group-item">Peso en Kg: {{ $producto->weightKg }}</li>
                </ul>
                <div class="card-body">
                    <form action="{{ route('productos.destroy', $producto->id) }}" method="post">
                        <a href="#" class="card-link">Ver mas</a>
                        <a href="{{ route('productos.edit', $producto->id) }}" class="card-link">Editar</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
        <br>
    @empty
        <div class="null-database">
            <h3>No hay registros de productos en la base de datos</h3>
        </div>
    @endforelse
</div>

<div>
    <br>
    {{ $productos->links() }}
    <br>
</div>

@endsection

resources/views/promociones/create.blade.php
@extends('layout.layout')

@section('title', 'Agregar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Agregar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.store')}}" method="POST">

      @csrf  {{-- //token de seguridad --}}

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5"></textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" name="price" id="price" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date"  class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Guardar Producto">
   </form>
</div>
@endsection

resources/views/promociones/edit.blade.php
@extends('layout.layout')

@section('title', 'Editar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Editar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.update', $producto->id)}}" method="POST">

      @csrf  {{-- //token de seguridad --}}
      @method('PUT')

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" value="{{ $producto->name }}" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5">{{ $producto->description }}</textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" value="{{$producto->price}}" name="price" id="" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date" value="{{$producto->price}}" class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" value="{{ $producto->stock }}" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" value="{{$producto->weightKg}}" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" value="{{ $producto->imgLink }}" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Actualizar Producto">
   </form>
</div>
@endsection

resources/views/promociones/index.blade.php
@extends('layout.layout')

@section('title', 'Productos')

@section('content')

@section('sectionInNav')
    <div class="navbar nav">
        <li class="nav-item">
            <a class="nav-link nav-item active" href="#">Productos Registrados : {{ $count }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link nav-item active" style="color: blue;" href="{{ route('productos.create') }}">Registrar Producto</a>
        </li>
    </div>
@endsection

<div class="row">
    {{-- loops through all the products in products 
         variable passed from index funtion in ProductoController --}}
    @forelse ($productos as $producto)

        <div class="col-sm-4 ">
            <div class="card bg-light border-dark" style="max-width: 24rem;">
                <img src="{{ $producto->imgLink }}" class="card-img" alt="" width="50">
                <div class="card-body">
                    <h2 class="card-title"><em>{{ $producto->name }}</em></h2>
                    <p class="card-text">{{ $producto->description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">${{ $producto->price }}</li>
                    <li class="list-group-item">Stock en almacen: {{ $producto->stock }}</li>
                    <li class="list-group-item">Fecha de caducidad: {{ $producto->expiration }}</li>
                    <li class="list-group-item">Peso en Kg: {{ $producto->weightKg }}</li>
                </ul>
                <div class="card-body">
                    <form action="{{ route('productos.destroy', $producto->id) }}" method="post">
                        <a href="#" class="card-link">Ver mas</a>
                        <a href="{{ route('productos.edit', $producto->id) }}" class="card-link">Editar</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
        <br>
    @empty
        <div class="null-database">
            <h3>No hay registros de productos en la base de datos</h3>
        </div>
    @endforelse
</div>

<div>
    <br>
    {{ $productos->links() }}
    <br>
</div>

@endsection

resources/views/ventas/create.blade.php
@extends('layout.layout')

@section('title', 'Agregar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Agregar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.store')}}" method="POST">

      @csrf  {{-- //token de seguridad --}}

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5"></textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" name="price" id="price" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date"  class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Guardar Producto">
   </form>
</div>
@endsection

resources/views/ventas/edit.blade.php
@extends('layout.layout')

@section('title', 'Editar Producto')

@section('content')

   @section('sectionInNav')
      <div>
         <li class="nav-link nav-item active">
            <h4 >Editar producto</h4>
         </li>
      </div>
   @endsection

   <div class="jumbotron">
   <form action="{{ route('productos.update', $producto->id)}}" method="POST">

      @csrf  {{-- //token de seguridad --}}
      @method('PUT')

      <div class="mb-3">
         <label for="">Producto: </label>
         <input type="text"  class="form-control" value="{{ $producto->name }}" name="name" id="name" required maxlength="100">
      </div>
      <div class="mb-3">
         <label for="">Descripción: </label>
         <textarea name="description"  class="form-control" id="" cols="30" rows="5">{{ $producto->description }}</textarea>
      </div>
      <div class="mb-3">
         <label for="">Precio: </label>
         <input type="text"  class="form-control" value="{{$producto->price}}" name="price" id="" required maxlength="7">
      </div>
      <div class="mb-3">
         <label for="">Fecha de caducidad: </label>
         <input type="date" value="{{$producto->price}}" class="form-control" name="expiration">
      </div>
      <div class="mb-3">
         <label for="">En stock: </label>
         <input type="number"  class="form-control" value="{{ $producto->stock }}" name="stock" id="" min="1" max="1000">
      </div>
      <div class="mb-3">
         <label for="">Peso en Kg: </label>
         <input type="text" class="form-control" value="{{$producto->weightKg}}" name="weightKg" id="" required>
      </div>
      <div class="mb-3">
         <label for="">Link de imagen: </label>
         <input type="text"  class="form-control" value="{{ $producto->imgLink }}" name="imgLink" id="" >
      </div>
      <input type="submit" class="btn btn-secondary" value="Actualizar Producto">
   </form>
</div>
@endsection

resources/views/ventas/index.blade.php
@extends('layout.layout')

@section('title', 'Productos')

@section('content')

@section('sectionInNav')
    <div class="navbar nav">
        <li class="nav-item">
            <a class="nav-link nav-item active" href="#">Productos Registrados : {{ $count }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link nav-item active" style="color: blue;" href="{{ route('productos.create') }}">Registrar Producto</a>
        </li>
    </div>
@endsection

<div class="row">
    {{-- loops through all the products in products 
         variable passed from index funtion in ProductoController --}}
    @forelse ($productos as $producto)

        <div class="col-sm-4 ">
            <div class="card bg-light border-dark" style="max-width: 24rem;">
                <img src="{{ $producto->imgLink }}" class="card-img" alt="" width="50">
                <div class="card-body">
                    <h2 class="card-title"><em>{{ $producto->name }}</em></h2>
                    <p class="card-text">{{ $producto->description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">${{ $producto->price }}</li>
                    <li class="list-group-item">Stock en almacen: {{ $producto->stock }}</li>
                    <li class="list-group-item">Fecha de caducidad: {{ $producto->expiration }}</li>
                    <li class="list-group-item">Peso en Kg: {{ $producto->weightKg }}</li>
                </ul>
                <div class="card-body">
                    <form action="{{ route('productos.destroy', $producto->id) }}" method="post">
                        <a href="#" class="card-link">Ver mas</a>
                        <a href="{{ route('productos.edit', $producto->id) }}" class="card-link">Editar</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
        <br>
    @empty
        <div class="null-database">
            <h3>No hay registros de productos en la base de datos</h3>
        </div>
    @endforelse
</div>

<div>
    <br>
    {{ $productos->links() }}
    <br>
</div>

@endsection